import dayjs from "dayjs";

export type UserRole = "Vận động viên" | "HLV" | "Cục Thể dục Thể thao" | "Khác";
export type Sport = "shooting" | "archery" | "taekwondo" | "boxing";
export type Gender = "male" | "female" | "other";

export type User = {
	id: string;
	name: string;
	avatar?: string;
	email?: string;
	phone?: string;
	address?: { city?: string; country?: string; state?: string; street?: string };
	createdAt?: Date;
	age?: number;
	status?: "Đang hoạt động" | "Tạm ngưng";
	password: string;
	role: UserRole;
	sport?: Sport;
	gender?: Gender;
	birthday?: string;
};

export const users: User[] = [
	{
		id: "ATH-010",
		name: "Nguyễn Văn J",
		avatar: "/assets/avatar-10.png",
		email: "athlete.j@dreamax.vn",
		phone: "0909 010 010",
		address: { city: "Nha Trang", country: "VN", state: "Khánh Hòa", street: "10 Trần Phú" },
		createdAt: dayjs().subtract(1, "day").toDate(),
		age: 23,
		status: "Đang hoạt động",
		password: "1234",
		role: "Vận động viên",
		sport: "shooting",
		gender: "male",
		birthday: "2002-03-10",
	},
	{
		id: "ATH-009",
		name: "Nguyễn Văn I",
		avatar: "/assets/avatar-9.png",
		email: "athlete.i@dreamax.vn",
		phone: "0909 009 009",
		address: { city: "Cần Thơ", country: "VN", state: "Cần Thơ", street: "9 Lý Tự Trọng" },
		createdAt: dayjs().subtract(3, "days").toDate(),
		age: 27,
		status: "Đang hoạt động",
		password: "1234",
		role: "HLV",
		sport: "archery",
		gender: "male",
		birthday: "1998-07-22",
	},
	{
		id: "ATH-008",
		name: "Nguyễn Văn H",
		avatar: "/assets/avatar-8.png",
		email: "athlete.h@dreamax.vn",
		phone: "0908 008 008",
		address: { city: "Vũng Tàu", country: "VN", state: "BR-VT", street: "8 Quang Trung" },
		createdAt: dayjs().subtract(5, "days").toDate(),
		age: 22,
		status: "Tạm ngưng",
		password: "1234",
		role: "Vận động viên",
		sport: "taekwondo",
		gender: "female",
		birthday: "2003-11-18",
	},
	{
		id: "ATH-007",
		name: "Nguyễn Văn G",
		avatar: "/assets/avatar-7.png",
		email: "athlete.g@dreamax.vn",
		phone: "0907 007 007",
		address: { city: "Đà Lạt", country: "VN", state: "Lâm Đồng", street: "7 Phan Đình Phùng" },
		createdAt: dayjs().subtract(7, "days").toDate(),
		age: 25,
		status: "Đang hoạt động",
		password: "1234",
		role: "Cục Thể dục Thể thao",
		sport: "boxing",
		gender: "male",
		birthday: "2000-06-03",
	},
	{
		id: "ATH-006",
		name: "Nguyễn Văn F",
		avatar: "/assets/avatar-6.png",
		email: "athlete.f@dreamax.vn",
		phone: "0906 006 006",
		address: { city: "Hải Phòng", country: "VN", state: "Hải Phòng", street: "6 Cát Dài" },
		createdAt: dayjs().subtract(8, "days").toDate(),
		age: 21,
		status: "Đang hoạt động",
		password: "1234",
		role: "Khác",
		sport: "shooting",
		gender: "female",
		birthday: "2004-01-14",
	},
	{
		id: "ATH-005",
		name: "Nguyễn Văn E",
		avatar: "/assets/avatar-5.png",
		email: "athlete.e@dreamax.vn",
		phone: "0905 005 005",
		address: { city: "Biên Hòa", country: "VN", state: "Đồng Nai", street: "5 Phạm Văn Thuận" },
		createdAt: dayjs().subtract(10, "days").toDate(),
		age: 28,
		status: "Tạm ngưng",
		password: "1234",
		role: "HLV",
		sport: "archery",
		gender: "female",
		birthday: "1997-12-02",
	},
	{
		id: "ATH-004",
		name: "Nguyễn Văn D",
		avatar: "/assets/avatar-4.png",
		email: "athlete.d@dreamax.vn",
		phone: "0904 004 004",
		address: { city: "Đà Nẵng", country: "VN", state: "Đà Nẵng", street: "4 Bạch Đằng" },
		createdAt: dayjs().subtract(12, "days").toDate(),
		age: 24,
		status: "Đang hoạt động",
		password: "1234",
		role: "Vận động viên",
		sport: "taekwondo",
		gender: "male",
		birthday: "2001-08-30",
	},
	{
		id: "ATH-003",
		name: "Nguyễn Văn C",
		avatar: "/assets/avatar-3.png",
		email: "athlete.c@dreamax.vn",
		phone: "0903 003 003",
		address: { city: "TP.HCM", country: "VN", state: "Hồ Chí Minh", street: "3 Nguyễn Huệ" },
		createdAt: dayjs().subtract(14, "days").toDate(),
		age: 26,
		status: "Đang hoạt động",
		password: "1234",
		role: "HLV",
		sport: "boxing",
		gender: "male",
		birthday: "1999-04-05",
	},
	{
		id: "ATH-002",
		name: "Nguyễn Văn B",
		avatar: "/assets/avatar-2.png",
		email: "athlete.b@dreamax.vn",
		phone: "0902 002 002",
		address: { city: "Hà Nội", country: "VN", state: "Hà Nội", street: "2 Tràng Tiền" },
		createdAt: dayjs().subtract(16, "days").toDate(),
		age: 20,
		status: "Tạm ngưng",
		password: "1234",
		role: "Khác",
		sport: "shooting",
		gender: "male",
		birthday: "2005-09-19",
	},
	{
		id: "ATH-001",
		name: "Nguyễn Văn A",
		avatar: "/assets/avatar-1.png",
		email: "athlete.a@dreamax.vn",
		phone: "0901 001 001",
		address: { city: "Hà Nội", country: "VN", state: "Hà Nội", street: "1 Hoàn Kiếm" },
		createdAt: dayjs().subtract(20, "days").toDate(),
		age: 23,
		status: "Đang hoạt động",
		password: "1234",
		role: "Vận động viên",
		sport: "archery",
		gender: "male",
		birthday: "2002-10-11",
	},
];
